server:
  port: ${PORT}
address:
  domain: ${DOMAIN_ADDRESS}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: ${DDL_TYPE}
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
    bootstrap-servers: ${KAFKA_SERVER}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SECRETKEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}

